language: rust
sudo: required
os:
- linux
- osx
rust:
- nightly-2019-09-05
services:
- docker
before_script:
- rustup component add rustfmt
- rustup component add clippy
script:
  # Require `cargo fmt` to have been run.
  - cargo fmt -- --check
  # Build the code.
  - cargo build --verbose
  # Run the tests.
  - cargo test --verbose
  # Require clippy to pass without warnings. This also fails for regular Rust
  # warnings.
  - cargo clippy -- -D warnings
before_deploy:
  #- cargo doc
  - ./build-release bigml-parallel "${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
deploy:
  - provider: releases
    api_key:
      secure: kzZWLFJfQG/hwCCcRds+6wfG0JrDX5BKSYsIxl2xN+0VyDVH24gaa2kf0tHNAOTBrNkPNDsIP/TP3HQRU+barWXU+/oqb6+wHxKhrxnqbt3m4nLdJpTneWOQiA9gGuhYHfai/kOMllaJ6h9IeO99lI3PtHo3NF/CZWWNRYnX77bGXSLpDo4rvdcUmo0uaC7PWGPnnqjh8Q+8Upim/knNRz3OAy4IlIyoMhV58Y1zHHd1fN4xgCbj+uMShGTPmb0E9RSrkl9BtZC4nexiHsqK+QJppiMj+7gIE0E9JVNrB9xFOzAcAIgUcYXEL/WATe1EMbQFzaHwZTEVF9fHsTIbUrS21aZ7UQn91GjwldW/Fn2OoP4k5vt8A5vDyC4Yfugn8voaQJPdHW0jNGutkeB34gLaDXBAOQmLjon9vbaLumW1brEekkc4JptjAVO7yjuVnka0nwkKBsF+WxFIkrI5NwAwAgZL0dDRiS5A2vPr/XsWqFkLdueORbX1I9JOzt/yBcOicch12yIEJj48pIG5lFRrBXYg8qhvpHqGMJK3AddtMstciyxYaQEy7VKJljOk0ZKD/g9Yh27iBoXZXFb0qqifMIQA8NQbkncPzFR7C19Kuwy7cC6FZM4wkI+G7F7SdVC18XEsXYWkDCiFovPzD2YIGmhF7RadnqTqRawhUMs=
    file_glob: true
    file: "bigml-parallel-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*"
    skip_cleanup: true
    on:
      tags: true
  #- provider: pages
  #  skip-cleanup: true
  #  local-dir: target/doc
  #  keep-history: true
  #  github-token: $GITHUB_TOKEN
  #  on:
  #    tags: true
  #    condition: $TRAVIS_OS_NAME = linux
