[package]
name = "bigml"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]

[dev-dependencies]
env_logger = "0.3.5"

[dependencies]
error-chain = "0.5.0"
lazy_static = "0.2.2"
mime = "0.2.2"
multipart = { version = "0.9.0-alpha.2", default-features = false, features = ["client"] }
reqwest = "0.1.0"
url = "1.2.3"
