[package]
name = "bigml-parallel"
version = "0.4.0-alpha.4"
authors = ["Eric Kidd <git@randomhacks.net>"]
edition = "2018"

description = "CLI tool for executing multiple BigML scripts in parallel"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/faradayio/bigml-rs"
documentation = "https://github.com/faradayio/bigml-rs/tree/master/bigml-parallel"

[dev-dependencies]
cli_test_dir = "0.1.5"

[dependencies]
bigml = { version = "=0.4.0-alpha.4", path = "../bigml" }
bytes = "0.4.12"
common_failures = "0.1.1"
# This makes the executable bigger, but it makes --help much nicer.
clap = { version = "2", features = ["wrap_help"] }
env_logger = "0.7"
failure = "0.1.5"
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }
log = "0.4"
serde = { version = "1" }
serde_json = "1.0"
# This is pretty heavyweight, but it's easy to set up and nice for users.
structopt = "0.3.4"
tokio = "0.1.22"
