[package]
name = "bigml-parallel"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]
edition = "2018"

[dev-dependencies]
cli_test_dir = "0.1.5"

[dependencies]
bigml = { path = "../bigml" }
common_failures = "0.1.1"
env_logger = "0.6"
failure = "0.1.5"
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }
log = "0.4"
serde = { version = "1" }
serde_json = "1.0"
# This is pretty heavyweight, but it's easy to set up and nice for users.
structopt = "0.2.18"
tokio = "0.1.22"
